name: Use a secret

on:
  workflow_dispatch:
    inputs:
      access_key_id:
        description: 'Access key to compare'
        required: true
        type: string



jobs:
  top-secret:
    runs-on: ubuntu-latest

    steps:
      # These are read by default from .env
      - name: Environment
        run: echo "My env value is ${{ env.VALUE_FROM_ENV }}"

      # A secret could be the GH_TOKEN
      - name: Tell me a secret!
        run: echo "My secret is ${{ secrets.MY_SECRET }}"

      - name: All secrets
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}